
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "branch": "master",
 "dirty": false,
 "error": null,
 "full-revisionid": "cb2e0d449f607bbc89c7ad13c983a0cf11bbfdee",
 "version": "1.003"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
